name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/s24480/2025-asi

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/s24480/2025-asi:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PREDYKCJAKOSZTUPRZEJAZDU_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PREDYKCJAKOSZTUPRZEJAZDU_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PREDYKCJAKOSZTUPRZEJAZDU_AZURE_SUBSCRIPTION_ID }}

      - name: Push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: predykcja-kosztu-przejazdu
          registryUrl: ghcr.io
          resourceGroup: asi
          registryUsername: ${{ secrets.PREDYKCJAKOSZTUPRZEJAZDU_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PREDYKCJAKOSZTUPRZEJAZDU_REGISTRY_PASSWORD }}
          imageToDeploy: ghcr.io/s24480/predykcja-kosztu-przejazdu:${{ github.sha }}
